FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base

WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["NuGet.config", "./"]

COPY ["src/FCG.Payments.Worker/FCG.Payments.Worker.csproj", "src/FCG.Payments.Worker/"]
COPY ["src/FCG.Payments.Application/FCG.Payments.Application.csproj", "src/FCG.Payments.Application/"]
COPY ["src/FCG.Payments.Domain/FCG.Payments.Domain.csproj", "src/FCG.Payments.Domain/"]
COPY ["src/FCG.Payments.Infrastructure/FCG.Payments.Infrastructure.csproj", "src/FCG.Payments.Infrastructure/"]

RUN dotnet restore "src/FCG.Payments.Worker/FCG.Payments.Worker.csproj" \
    --configfile "/src/NuGet.config"

COPY . .

RUN dotnet publish "src/FCG.Payments.Worker/FCG.Payments.Worker.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore \
    /p:UseAppHost=false


FROM base AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FCG.Payments.Worker.dll"]