apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-payments-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"

  DOTNET_ENVIRONMENT: "Development"

  Jwt__Issuer: "FCG.Users.Api"
  Jwt__Audience: "FCG.CloudGames"
  Jwt__ExpirationMinutes: "60"

  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: "/"
  RabbitMq__OrderPlacedQueue: "payments-order-placed"

  Notifications__BaseUrl: "http://fcg-notifications-functions"
